spring:
  application:
    name: opendata-crud
  datasource:
    url: jdbc:mariadb://localhost:3306/petanque
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 8080